"""added default to user role model 

Revision ID: 701a680bd1f2
Revises: 8a2fd58c62c4
Create Date: 2024-05-15 21:55:48.252282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701a680bd1f2'
down_revision = '8a2fd58c62c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
